package entity;
// Generated Apr 13, 2018 11:49:02 AM by Hibernate Tools 4.3.1



/**
 * BookingDetailId generated by hbm2java
 */
public class BookingDetailId  implements java.io.Serializable {


     private String bookingId;
     private String menuId;

    public BookingDetailId() {
    }

    public BookingDetailId(String bookingId, String menuId) {
       this.bookingId = bookingId;
       this.menuId = menuId;
    }
   
    public String getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(String bookingId) {
        this.bookingId = bookingId;
    }
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BookingDetailId) ) return false;
		 BookingDetailId castOther = ( BookingDetailId ) other; 
         
		 return ( (this.getBookingId()==castOther.getBookingId()) || ( this.getBookingId()!=null && castOther.getBookingId()!=null && this.getBookingId().equals(castOther.getBookingId()) ) )
 && ( (this.getMenuId()==castOther.getMenuId()) || ( this.getMenuId()!=null && castOther.getMenuId()!=null && this.getMenuId().equals(castOther.getMenuId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBookingId() == null ? 0 : this.getBookingId().hashCode() );
         result = 37 * result + ( getMenuId() == null ? 0 : this.getMenuId().hashCode() );
         return result;
   }   


}


