package entity;
// Generated Apr 13, 2018 11:49:02 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Booking generated by hbm2java
 */
public class Booking  implements java.io.Serializable {


     private String bookingId;
     private Concept concept;
     private Customer customer;
     private Room room;
     private User user;
     private String description;
     private Date bookingDate;
     private String shift;
     private Set bookingDetails = new HashSet(0);

    public Booking() {
    }

	
    public Booking(String bookingId) {
        this.bookingId = bookingId;
    }
    public Booking(String bookingId, Concept concept, Customer customer, Room room, User user, String description, Date bookingDate, String shift, Set bookingDetails) {
       this.bookingId = bookingId;
       this.concept = concept;
       this.customer = customer;
       this.room = room;
       this.user = user;
       this.description = description;
       this.bookingDate = bookingDate;
       this.shift = shift;
       this.bookingDetails = bookingDetails;
    }
   
    public String getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(String bookingId) {
        this.bookingId = bookingId;
    }
    public Concept getConcept() {
        return this.concept;
    }
    
    public void setConcept(Concept concept) {
        this.concept = concept;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Room getRoom() {
        return this.room;
    }
    
    public void setRoom(Room room) {
        this.room = room;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getBookingDate() {
        return this.bookingDate;
    }
    
    public void setBookingDate(Date bookingDate) {
        this.bookingDate = bookingDate;
    }
    public String getShift() {
        return this.shift;
    }
    
    public void setShift(String shift) {
        this.shift = shift;
    }
    public Set getBookingDetails() {
        return this.bookingDetails;
    }
    
    public void setBookingDetails(Set bookingDetails) {
        this.bookingDetails = bookingDetails;
    }




}


