package entity;
// Generated Apr 13, 2018 11:49:02 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Concept generated by hbm2java
 */
public class Concept  implements java.io.Serializable {


     private String conceptId;
     private String color;
     private String table;
     private String background;
     private String folower;
     private String price;
     private Set bookings = new HashSet(0);

    public Concept() {
    }

	
    public Concept(String conceptId) {
        this.conceptId = conceptId;
    }
    public Concept(String conceptId, String color, String table, String background, String folower, String price, Set bookings) {
       this.conceptId = conceptId;
       this.color = color;
       this.table = table;
       this.background = background;
       this.folower = folower;
       this.price = price;
       this.bookings = bookings;
    }
   
    public String getConceptId() {
        return this.conceptId;
    }
    
    public void setConceptId(String conceptId) {
        this.conceptId = conceptId;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getTable() {
        return this.table;
    }
    
    public void setTable(String table) {
        this.table = table;
    }
    public String getBackground() {
        return this.background;
    }
    
    public void setBackground(String background) {
        this.background = background;
    }
    public String getFolower() {
        return this.folower;
    }
    
    public void setFolower(String folower) {
        this.folower = folower;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public Set getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set bookings) {
        this.bookings = bookings;
    }




}


