package entity;
// Generated Apr 10, 2018 1:15:47 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

    private String customterId;
    private String firstName;
    private String lastName;
    private String phone;
    private String address;
    private String gender;
    private Set bookings = new HashSet(0);

    public Customer() {
    }

    public Customer(String customterId) {
        this.customterId = customterId;
    }

    public Customer(String customterId, String firstName, String lastName, String phone, String address, String gender, Set bookings) {
        this.customterId = customterId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.address = address;
        this.gender = gender;
        this.bookings = bookings;
    }

    public Customer(String id, String text, String text0, String text1, String text2, String sex) {
        this.customterId = id;
        this.firstName = text;
        this.lastName = text0;
        this.phone = text1;
        this.address = text2;
        this.gender = sex;
    }

    public String getCustomterId() {
        return this.customterId;
    }

    public void setCustomterId(String customterId) {
        this.customterId = customterId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Set getBookings() {
        return this.bookings;
    }

    public void setBookings(Set bookings) {
        this.bookings = bookings;
    }

}
