package entity;
// Generated Apr 1, 2018 3:13:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javafx.scene.control.CheckBox;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private String menuId;
     private TitleMenu titleMenu;
     private String menuName;
     private String price;
     private String description;
     private String image;
     private Boolean status;
     // isSelect
      private Boolean isSelect;
   
     private Set bookingDetails = new HashSet(0);
    

    public Menu() {
    }

	
    public Menu(String menuId) {
        this.menuId = menuId;
    }
    public Menu(String menuId, TitleMenu titleMenu, String menuName, String price, String description, String image, Boolean status, Boolean isSelect, Set bookingDetails) {
       this.menuId = menuId;
       this.titleMenu = titleMenu;
       this.menuName = menuName;
       this.price = price;
       this.description = description;
       this.image = image;
       this.status = status;
       this.isSelect=isSelect;
       this.bookingDetails = bookingDetails;
       // checkbox
       //this.select=new CheckBox();
    }
   
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
    public TitleMenu getTitleMenu() {
        return this.titleMenu;
    }
    
    public void setTitleMenu(TitleMenu titleMenu) {
        this.titleMenu = titleMenu;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getBookingDetails() {
        return this.bookingDetails;
    }

    public Boolean getIsSelect() {
        return isSelect;
    }

    public void setIsSelect(Boolean isSelect) {
        this.isSelect = isSelect;
    }
    
    
    public void setBookingDetails(Set bookingDetails) {
        this.bookingDetails = bookingDetails;
    }
    // checkbox
//    public CheckBox getSelect(){
//        return select;
//    }
//    public void setSelect(CheckBox select){
//        this.select=select;
//    }




}


