package entity;
// Generated Apr 10, 2018 1:15:47 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

    private String menuId;
    private TitleMenu titleMenu;
    private String menuName;
    private String price;
    private String description;
    private String image;
    private Boolean status;
    private Boolean isSelect;
    private Set bookingDetails = new HashSet(0);

    public Menu() {
    }

    public Menu(String menuId) {
        this.menuId = menuId;
    }

    public Menu(String menuId, TitleMenu titleMenu, String menuName, String price, String description, String image, Boolean status, Boolean isSelect, Set bookingDetails) {
        this.menuId = menuId;
        this.titleMenu = titleMenu;
        this.menuName = menuName;
        this.price = price;
        this.description = description;
        this.image = image;
        this.status = status;
        this.isSelect = isSelect;
        this.bookingDetails = bookingDetails;
    }

    public Menu(String menuId, TitleMenu titleMenu, String menuName, String price, String description, String image, Boolean status, boolean b) {
        this.menuId = menuId;
        this.titleMenu = titleMenu;
        this.menuName = menuName;
        this.price = price;
        this.description = description;
        this.image = image;
        this.status = status;
        this.isSelect = b;
    }

    public String getMenuId() {
        return this.menuId;
    }

    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    public TitleMenu getTitleMenu() {
        return this.titleMenu;
    }

    public void setTitleMenu(TitleMenu titleMenu) {
        this.titleMenu = titleMenu;
    }

    public String getMenuName() {
        return this.menuName;
    }

    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Boolean getIsSelect() {
        return this.isSelect;
    }

    public void setIsSelect(Boolean isSelect) {
        this.isSelect = isSelect;
    }

    public Set getBookingDetails() {
        return this.bookingDetails;
    }

    public void setBookingDetails(Set bookingDetails) {
        this.bookingDetails = bookingDetails;
    }

}
