package entity;
// Generated Apr 3, 2018 4:37:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String id;
     private String userName;
     private String password;
     private String firstName;
     private String lastName;
     private String role;
     private String active;
     private String address;
     private String email;
     private String gender;
     private String image;
     private Set bookings = new HashSet(0);

    public User() {
    }

	
    public User(String id, String userName, String password, String role, String active) {
        this.id = id;
        this.userName = userName;
        this.password = password;
        this.role = role;
        this.active = active;
    }
    public User(String id, String userName, String password, String firstName, String lastName, String role, String active, String address, String email, String gender, String image, Set bookings) {
       this.id = id;
       this.userName = userName;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.role = role;
       this.active = active;
       this.address = address;
       this.email = email;
       this.gender = gender;
       this.image = image;
       this.bookings = bookings;
    }
    public User(String id, String userName, String password, String firstName, String lastName, String role, String active, String address, String email, String gender) {
       this.id = id;
       this.userName = userName;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.role = role;
       this.active = active;
       this.address = address;
       this.email = email;
       this.gender = gender;
    }

    public User(User item) {
        this.id = item.getId();
       this.userName = item.getUserName();
       this.password = item.getPassword();
       this.firstName = item.getFirstName();
       this.lastName = item.getLastName();
       this.role = item.getRole();
       this.active = item.getActive();
       this.address = item.getActive();
       this.email = item.getEmail();
       this.gender = item.getGender();
       this.image = item.getImage();
    }

   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set bookings) {
        this.bookings = bookings;
    }




}


